sed -i -e 's|32-07|32-07-3|g' out_sample_list_sample_grid.13TeV_25ns.mcdata_a.HIGG5D2.txt

# and for a list of variables to be replaced with the values stored in the variables
CONFIG="file.cfg"
VARIABLEs="NUMBEROFEVENTS SAMPLES LEPCHANNEL GRLFILES ILUMICALCFILES CONFIGFILES DOXBBTAG DOCLOSEBYISOCORR REGULARJETCONTAINER REGULARJETALGONAME METCONTAINER FATJETCONTAINER TRUTHWZJETCONTAINER METTRIGGEREMULATION DEBUG NOMINALONLY VTAG SUBMIT USEDSITE EXCLUDEDSITE DESTSE USENEWCODE ALLOWTASKDUPLICATION NRGBPERJOB NRFILESPERJOB COMPUTECODETTBARDECAY QGTAGGER SAVEQGVARIABLES"
for VARIABLE in ${VARIABLEs}
do
    # echo "VARIABLE=${VARIABLE}"
    COMMAND="echo ${VARIABLE}=\$${VARIABLE}"
    # echo "COMMAND=${COMMAND}"
    eval ${COMMAND}
    # sed -i -e 's|NRFILESPERJOB|'"${NRFILESPERJOB}"'|g' ${CONFIG}
    COMMAND="sed -i -e 's|${VARIABLE}|'\"\${${VARIABLE}}\"'|g' ${CONFIG}"
    # echo "COMMAND=${COMMAND}"
    eval ${COMMAND}
done
